#!/bin/bash
AUDIO="/Users/sahbeewah/Dev/chloe-learns-math/assets/audio/en/spelling"
V="en-US-AnaNeural"

gen() {
  local word="$1"
  local sentence="$2"
  if [ -f "$AUDIO/${word}-word.mp3" ]; then
    echo "SKIP $word"
    return
  fi
  edge-tts --text "$word" --voice "$V" --write-media "$AUDIO/${word}-word.mp3" 2>/dev/null
  edge-tts --text "$sentence" --voice "$V" --write-media "$AUDIO/${word}-sentence.mp3" 2>/dev/null
  echo "OK $word"
}

gen "the" "The ball is on the table."
gen "of" "She ate a piece of cake."
gen "and" "Mom and dad love you."
gen "a" "I see a big star."
gen "to" "Let's go to the park."
gen "in" "The frog is in the pond."
gen "is" "This is my favorite toy."
gen "you" "You are so smart!"
gen "that" "Look at that rainbow!"
gen "it" "It is a sunny day."
gen "he" "He likes to draw."
gen "for" "This gift is for you."
gen "was" "She was very happy."
gen "on" "The cat is on the bed."
gen "are" "We are best friends."
gen "as" "She ran as fast as she could."
gen "with" "Come play with me."
gen "his" "He lost his shoe."
gen "they" "They went to the zoo."
gen "at" "Look at the stars."
gen "be" "I want to be a doctor."
gen "this" "This is really cool!"
gen "from" "A letter from grandma."
gen "I" "I love to read books."
gen "have" "I have a pet fish."
gen "or" "Do you want milk or juice?"
gen "by" "She sat by the window."
gen "one" "I have one red crayon."
gen "had" "He had a fun day."
gen "not" "Do not touch the stove."
gen "but" "I tried but it was hard."
gen "what" "What is your name?"
gen "all" "We ate all the cookies."
gen "were" "They were playing outside."
gen "when" "Tell me when you are ready."
gen "we" "We love to sing songs."
gen "there" "There is a bird in the tree."
gen "can" "You can do it!"
gen "an" "She ate an apple."
gen "your" "Is this your teddy bear?"
gen "which" "Which color do you like?"
gen "their" "They brought their lunch."
gen "said" "She said hello to everyone."
gen "if" "If it rains we stay inside."
gen "do" "What do you want to play?"
gen "will" "I will help you."
gen "each" "Each child got a sticker."
gen "about" "Tell me about your day."
gen "how" "How did you do that?"
gen "up" "The kite flew up high."
gen "out" "Let's go out and play."
gen "them" "Give them a big hug."
gen "then" "First eat then play."
gen "she" "She loves to dance."
gen "many" "So many pretty flowers!"
gen "some" "Can I have some water?"
gen "so" "You did so well!"
gen "these" "Look at these butterflies."
gen "would" "Would you like a cookie?"
gen "other" "Try the other one."
gen "into" "The bunny hopped into the hole."
gen "has" "She has a new puppy."
gen "more" "Can I have more please?"
gen "her" "Give her a high five."
gen "two" "I have two hands."
gen "like" "I like ice cream."
gen "him" "Tell him to come here."
gen "see" "Can you see the moon?"
gen "time" "It is time for bed."
gen "could" "She could jump so high."
gen "no" "No running in the house."
gen "make" "Let's make a sandcastle."
gen "than" "She is taller than me."
gen "first" "I finished first!"
gen "been" "I have been to the beach."
gen "its" "The dog wagged its tail."
gen "who" "Who wants to play?"
gen "now" "Let's go now!"
gen "people" "Many people came to the party."
gen "my" "This is my favorite song."
gen "made" "She made a pretty drawing."
gen "over" "The cow jumped over the moon."
gen "did" "You did a great job!"
gen "down" "Slide down the hill."
gen "only" "I have only one left."
gen "way" "This is the way home."
gen "find" "Can you find the hidden star?"
gen "use" "Use your inside voice."
gen "may" "May I have a turn?"
gen "water" "Drink some water please."
gen "long" "That is a long snake."
gen "little" "The little mouse ran away."
gen "very" "You are very kind."
gen "after" "We play after lunch."
gen "words" "Can you read these words?"
gen "called" "Mom called my name."
gen "just" "I just want to play."
gen "where" "Where is my teddy?"
gen "most" "She has the most stickers."
gen "know" "I know the answer!"

echo "ALL DONE"
